//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Host.Middleware.JCIC.JCICWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices", ConfigurationName="JCICWS.EPaymentImpl")]
    public interface EPaymentImpl {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginRequest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ICP.Host.Middleware.JCIC.JCICWS.RtnOutLoginBean Login(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginRequest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutLoginBean> LoginAsync(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginJsonRequest" +
            "", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginJsonRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string LoginJson(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginJsonRequest" +
            "", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/LoginJsonRespons" +
            "e")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> LoginJsonAsync(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryRequest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ICP.Host.Middleware.JCIC.JCICWS.RtnOutP11Bean P11Query(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryRequest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryResponse" +
            "")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutP11Bean> P11QueryAsync(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryJsonRequ" +
            "est", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryJsonResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string P11QueryJson(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryJsonRequ" +
            "est", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P11QueryJsonResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> P11QueryJsonAsync(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryRequest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ICP.Host.Middleware.JCIC.JCICWS.RtnOutP33Bean P33Query(string sessionId, string idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryRequest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryResponse" +
            "")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutP33Bean> P33QueryAsync(string sessionId, string idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryJsonRequ" +
            "est", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryJsonResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string P33QueryJson(string sessionId, string idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryJsonRequ" +
            "est", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/P33QueryJsonResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> P33QueryJsonAsync(string sessionId, string idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadReques" +
            "t", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ICP.Host.Middleware.JCIC.JCICWS.RtnOutPF01Bean PF01Upload(string sessionId, string main_code, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadReques" +
            "t", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadRespon" +
            "se")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutPF01Bean> PF01UploadAsync(string sessionId, string main_code, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadJsonRe" +
            "quest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadJsonRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string PF01UploadJson(string sessionId, string main_code, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadJsonRe" +
            "quest", ReplyAction="https://webservices.jcic.org.tw/EPaymentWebServices/EPaymentImpl/PF01UploadJsonRe" +
            "sponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> PF01UploadJsonAsync(string sessionId, string main_code, string content);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class RtnOutLoginBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string msgField;
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class RtnOutPF01Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class VAM033Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string criPlaceField;
        
        private string criDateField;
        
        private string docDateField;
        
        private string cnameField;
        
        private string invoiceNoField;
        
        private string remarkField;
        
        private string docNameField;
        
        private string relCodeField;
        
        private string relReasonField;
        
        private string relDateField;
        
        private string fillerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string criPlace {
            get {
                return this.criPlaceField;
            }
            set {
                this.criPlaceField = value;
                this.RaisePropertyChanged("criPlace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string criDate {
            get {
                return this.criDateField;
            }
            set {
                this.criDateField = value;
                this.RaisePropertyChanged("criDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
                this.RaisePropertyChanged("docDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cname {
            get {
                return this.cnameField;
            }
            set {
                this.cnameField = value;
                this.RaisePropertyChanged("cname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string invoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
                this.RaisePropertyChanged("invoiceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string docName {
            get {
                return this.docNameField;
            }
            set {
                this.docNameField = value;
                this.RaisePropertyChanged("docName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string relCode {
            get {
                return this.relCodeField;
            }
            set {
                this.relCodeField = value;
                this.RaisePropertyChanged("relCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string relReason {
            get {
                return this.relReasonField;
            }
            set {
                this.relReasonField = value;
                this.RaisePropertyChanged("relReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string relDate {
            get {
                return this.relDateField;
            }
            set {
                this.relDateField = value;
                this.RaisePropertyChanged("relDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string filler {
            get {
                return this.fillerField;
            }
            set {
                this.fillerField = value;
                this.RaisePropertyChanged("filler");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class VAM109Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataDateField;
        
        private string maincodeField;
        
        private string mainnoteField;
        
        private string noteField;
        
        private string fillerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataDate {
            get {
                return this.dataDateField;
            }
            set {
                this.dataDateField = value;
                this.RaisePropertyChanged("dataDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string maincode {
            get {
                return this.maincodeField;
            }
            set {
                this.maincodeField = value;
                this.RaisePropertyChanged("maincode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mainnote {
            get {
                return this.mainnoteField;
            }
            set {
                this.mainnoteField = value;
                this.RaisePropertyChanged("mainnote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string filler {
            get {
                return this.fillerField;
            }
            set {
                this.fillerField = value;
                this.RaisePropertyChanged("filler");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class RtnOutP33Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string msgField;
        
        private VAM021Bean[] vam021Field;
        
        private VAM109Bean[] vam109Field;
        
        private VAM033Bean[] vam033Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vam021", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public VAM021Bean[] vam021 {
            get {
                return this.vam021Field;
            }
            set {
                this.vam021Field = value;
                this.RaisePropertyChanged("vam021");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vam109", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public VAM109Bean[] vam109 {
            get {
                return this.vam109Field;
            }
            set {
                this.vam109Field = value;
                this.RaisePropertyChanged("vam109");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vam033", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public VAM033Bean[] vam033 {
            get {
                return this.vam033Field;
            }
            set {
                this.vam033Field = value;
                this.RaisePropertyChanged("vam033");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class VAM021Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldIdnField;
        
        private string newIdnField;
        
        private string opDateField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string oldIdn {
            get {
                return this.oldIdnField;
            }
            set {
                this.oldIdnField = value;
                this.RaisePropertyChanged("oldIdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string newIdn {
            get {
                return this.newIdnField;
            }
            set {
                this.newIdnField = value;
                this.RaisePropertyChanged("newIdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string opDate {
            get {
                return this.opDateField;
            }
            set {
                this.opDateField = value;
                this.RaisePropertyChanged("opDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class VAS011Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idnField;
        
        private string issueDateField;
        
        private string issueTypeField;
        
        private string birthDateField;
        
        private string picFreeField;
        
        private string issueLocField;
        
        private string answerField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
                this.RaisePropertyChanged("idn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string issueType {
            get {
                return this.issueTypeField;
            }
            set {
                this.issueTypeField = value;
                this.RaisePropertyChanged("issueType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string picFree {
            get {
                return this.picFreeField;
            }
            set {
                this.picFreeField = value;
                this.RaisePropertyChanged("picFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string issueLoc {
            get {
                return this.issueLocField;
            }
            set {
                this.issueLocField = value;
                this.RaisePropertyChanged("issueLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string answer {
            get {
                return this.answerField;
            }
            set {
                this.answerField = value;
                this.RaisePropertyChanged("answer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class VAI002Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataDate {
            get {
                return this.dataDateField;
            }
            set {
                this.dataDateField = value;
                this.RaisePropertyChanged("dataDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class RtnOutP11Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string msgField;
        
        private VAM021Bean[] vam021Field;
        
        private VAI002Bean[] vai002Field;
        
        private VAS011Bean[] vas011Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vam021", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public VAM021Bean[] vam021 {
            get {
                return this.vam021Field;
            }
            set {
                this.vam021Field = value;
                this.RaisePropertyChanged("vam021");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vai002", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public VAI002Bean[] vai002 {
            get {
                return this.vai002Field;
            }
            set {
                this.vai002Field = value;
                this.RaisePropertyChanged("vai002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vas011", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public VAS011Bean[] vas011 {
            get {
                return this.vas011Field;
            }
            set {
                this.vas011Field = value;
                this.RaisePropertyChanged("vas011");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.jcic.org.tw/EPaymentWebServices")]
    public partial class ParamInP11Bean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idnField;
        
        private string issueDateField;
        
        private string issueTypeField;
        
        private string birthDateField;
        
        private string picFreeField;
        
        private string issueLocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idn {
            get {
                return this.idnField;
            }
            set {
                this.idnField = value;
                this.RaisePropertyChanged("idn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string issueType {
            get {
                return this.issueTypeField;
            }
            set {
                this.issueTypeField = value;
                this.RaisePropertyChanged("issueType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string picFree {
            get {
                return this.picFreeField;
            }
            set {
                this.picFreeField = value;
                this.RaisePropertyChanged("picFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string issueLoc {
            get {
                return this.issueLocField;
            }
            set {
                this.issueLocField = value;
                this.RaisePropertyChanged("issueLoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EPaymentImplChannel : ICP.Host.Middleware.JCIC.JCICWS.EPaymentImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EPaymentImplClient : System.ServiceModel.ClientBase<ICP.Host.Middleware.JCIC.JCICWS.EPaymentImpl>, ICP.Host.Middleware.JCIC.JCICWS.EPaymentImpl {
        
        public EPaymentImplClient() {
        }
        
        public EPaymentImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EPaymentImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPaymentImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPaymentImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ICP.Host.Middleware.JCIC.JCICWS.RtnOutLoginBean Login(string userId, string password) {
            return base.Channel.Login(userId, password);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutLoginBean> LoginAsync(string userId, string password) {
            return base.Channel.LoginAsync(userId, password);
        }
        
        public string LoginJson(string userId, string password) {
            return base.Channel.LoginJson(userId, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginJsonAsync(string userId, string password) {
            return base.Channel.LoginJsonAsync(userId, password);
        }
        
        public ICP.Host.Middleware.JCIC.JCICWS.RtnOutP11Bean P11Query(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean) {
            return base.Channel.P11Query(sessionId, paramInP11Bean);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutP11Bean> P11QueryAsync(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean) {
            return base.Channel.P11QueryAsync(sessionId, paramInP11Bean);
        }
        
        public string P11QueryJson(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean) {
            return base.Channel.P11QueryJson(sessionId, paramInP11Bean);
        }
        
        public System.Threading.Tasks.Task<string> P11QueryJsonAsync(string sessionId, ICP.Host.Middleware.JCIC.JCICWS.ParamInP11Bean paramInP11Bean) {
            return base.Channel.P11QueryJsonAsync(sessionId, paramInP11Bean);
        }
        
        public ICP.Host.Middleware.JCIC.JCICWS.RtnOutP33Bean P33Query(string sessionId, string idn) {
            return base.Channel.P33Query(sessionId, idn);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutP33Bean> P33QueryAsync(string sessionId, string idn) {
            return base.Channel.P33QueryAsync(sessionId, idn);
        }
        
        public string P33QueryJson(string sessionId, string idn) {
            return base.Channel.P33QueryJson(sessionId, idn);
        }
        
        public System.Threading.Tasks.Task<string> P33QueryJsonAsync(string sessionId, string idn) {
            return base.Channel.P33QueryJsonAsync(sessionId, idn);
        }
        
        public ICP.Host.Middleware.JCIC.JCICWS.RtnOutPF01Bean PF01Upload(string sessionId, string main_code, string content) {
            return base.Channel.PF01Upload(sessionId, main_code, content);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.Middleware.JCIC.JCICWS.RtnOutPF01Bean> PF01UploadAsync(string sessionId, string main_code, string content) {
            return base.Channel.PF01UploadAsync(sessionId, main_code, content);
        }
        
        public string PF01UploadJson(string sessionId, string main_code, string content) {
            return base.Channel.PF01UploadJson(sessionId, main_code, content);
        }
        
        public System.Threading.Tasks.Task<string> PF01UploadJsonAsync(string sessionId, string main_code, string content) {
            return base.Channel.PF01UploadJsonAsync(sessionId, main_code, content);
        }
    }
}
