//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Host.AccountLink.KeyApiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeyApiServiceReference.KeyApiSoap")]
    public interface KeyApiSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  key 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponse GetValue(ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponse> GetValueAsync(ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  rawDataHex 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncrypt", ReplyAction="*")]
        ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse TripleDESEncrypt(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse> TripleDESEncryptAsync(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  encryptedHex 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecrypt", ReplyAction="*")]
        ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse TripleDESDecrypt(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse> TripleDESDecryptAsync(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValue", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequestBody Body;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetValueRequestBody() {
        }
        
        public GetValueRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponseBody Body;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValueResult;
        
        public GetValueResponseBody() {
        }
        
        public GetValueResponseBody(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncrypt", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody Body;
        
        public TripleDESEncryptRequest() {
        }
        
        public TripleDESEncryptRequest(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rawDataHex;
        
        public TripleDESEncryptRequestBody() {
        }
        
        public TripleDESEncryptRequestBody(string rawDataHex) {
            this.rawDataHex = rawDataHex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponseBody Body;
        
        public TripleDESEncryptResponse() {
        }
        
        public TripleDESEncryptResponse(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESEncryptResult;
        
        public TripleDESEncryptResponseBody() {
        }
        
        public TripleDESEncryptResponseBody(string TripleDESEncryptResult) {
            this.TripleDESEncryptResult = TripleDESEncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecrypt", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody Body;
        
        public TripleDESDecryptRequest() {
        }
        
        public TripleDESDecryptRequest(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptedHex;
        
        public TripleDESDecryptRequestBody() {
        }
        
        public TripleDESDecryptRequestBody(string encryptedHex) {
            this.encryptedHex = encryptedHex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponseBody Body;
        
        public TripleDESDecryptResponse() {
        }
        
        public TripleDESDecryptResponse(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESDecryptResult;
        
        public TripleDESDecryptResponseBody() {
        }
        
        public TripleDESDecryptResponseBody(string TripleDESDecryptResult) {
            this.TripleDESDecryptResult = TripleDESDecryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeyApiSoapChannel : ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyApiSoapClient : System.ServiceModel.ClientBase<ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap>, ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap {
        
        public KeyApiSoapClient() {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponse ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap.GetValue(ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string key) {
            ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest inValue = new ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest();
            inValue.Body = new ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequestBody();
            inValue.Body.key = key;
            ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponse retVal = ((ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).GetValue(inValue);
            return retVal.Body.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponse> ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap.GetValueAsync(ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest request) {
            return base.Channel.GetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.GetValueResponse> GetValueAsync(string key) {
            ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest inValue = new ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequest();
            inValue.Body = new ICP.Host.AccountLink.KeyApiServiceReference.GetValueRequestBody();
            inValue.Body.key = key;
            return ((ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).GetValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESEncrypt(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request) {
            return base.Channel.TripleDESEncrypt(request);
        }
        
        public string TripleDESEncrypt(string rawDataHex) {
            ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest inValue = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest();
            inValue.Body = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody();
            inValue.Body.rawDataHex = rawDataHex;
            ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse retVal = ((ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESEncrypt(inValue);
            return retVal.Body.TripleDESEncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse> ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESEncryptAsync(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request) {
            return base.Channel.TripleDESEncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse> TripleDESEncryptAsync(string rawDataHex) {
            ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest inValue = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest();
            inValue.Body = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody();
            inValue.Body.rawDataHex = rawDataHex;
            return ((ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESEncryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESDecrypt(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request) {
            return base.Channel.TripleDESDecrypt(request);
        }
        
        public string TripleDESDecrypt(string encryptedHex) {
            ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest inValue = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest();
            inValue.Body = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse retVal = ((ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESDecrypt(inValue);
            return retVal.Body.TripleDESDecryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse> ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESDecryptAsync(ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request) {
            return base.Channel.TripleDESDecryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse> TripleDESDecryptAsync(string encryptedHex) {
            ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest inValue = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest();
            inValue.Body = new ICP.Host.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            return ((ICP.Host.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESDecryptAsync(inValue);
        }
    }
}
