//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Batch.AppRssPush.KeyApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeyApi.KeyApiSoap")]
    public interface KeyApiSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  key 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.GetValueResponse GetValue(ICP.Batch.AppRssPush.KeyApi.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.GetValueResponse> GetValueAsync(ICP.Batch.AppRssPush.KeyApi.GetValueRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  rawData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncrypt", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponse TripleDESEncrypt(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponse> TripleDESEncryptAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  encryptedHex 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecrypt", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponse TripleDESDecrypt(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponse> TripleDESDecryptAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  rawData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncryptByKey", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponse TripleDESEncryptByKey(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncryptByKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponse> TripleDESEncryptByKeyAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  encryptedHex 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecryptByKey", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponse TripleDESDecryptByKey(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecryptByKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponse> TripleDESDecryptByKeyAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  data 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sign", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.SignResponse Sign(ICP.Batch.AppRssPush.KeyApi.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sign", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.SignResponse> SignAsync(ICP.Batch.AppRssPush.KeyApi.SignRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  signData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySign", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.VerifySignResponse VerifySign(ICP.Batch.AppRssPush.KeyApi.VerifySignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySign", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.VerifySignResponse> VerifySignAsync(ICP.Batch.AppRssPush.KeyApi.VerifySignRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  bankCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignTest", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.SignTestResponse SignTest(ICP.Batch.AppRssPush.KeyApi.SignTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignTest", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.SignTestResponse> SignTestAsync(ICP.Batch.AppRssPush.KeyApi.SignTestRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  bankCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySignTest", ReplyAction="*")]
        ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponse VerifySignTest(ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySignTest", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponse> VerifySignTestAsync(ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValue", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.GetValueRequestBody Body;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(ICP.Batch.AppRssPush.KeyApi.GetValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetValueRequestBody() {
        }
        
        public GetValueRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.GetValueResponseBody Body;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(ICP.Batch.AppRssPush.KeyApi.GetValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValueResult;
        
        public GetValueResponseBody() {
        }
        
        public GetValueResponseBody(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncrypt", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequestBody Body;
        
        public TripleDESEncryptRequest() {
        }
        
        public TripleDESEncryptRequest(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rawData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyLabel;
        
        public TripleDESEncryptRequestBody() {
        }
        
        public TripleDESEncryptRequestBody(string rawData, string keyLabel) {
            this.rawData = rawData;
            this.keyLabel = keyLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponseBody Body;
        
        public TripleDESEncryptResponse() {
        }
        
        public TripleDESEncryptResponse(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESEncryptResult;
        
        public TripleDESEncryptResponseBody() {
        }
        
        public TripleDESEncryptResponseBody(string TripleDESEncryptResult) {
            this.TripleDESEncryptResult = TripleDESEncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecrypt", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequestBody Body;
        
        public TripleDESDecryptRequest() {
        }
        
        public TripleDESDecryptRequest(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptedHex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyLabel;
        
        public TripleDESDecryptRequestBody() {
        }
        
        public TripleDESDecryptRequestBody(string encryptedHex, string keyLabel) {
            this.encryptedHex = encryptedHex;
            this.keyLabel = keyLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponseBody Body;
        
        public TripleDESDecryptResponse() {
        }
        
        public TripleDESDecryptResponse(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESDecryptResult;
        
        public TripleDESDecryptResponseBody() {
        }
        
        public TripleDESDecryptResponseBody(string TripleDESDecryptResult) {
            this.TripleDESDecryptResult = TripleDESDecryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptByKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptByKey", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequestBody Body;
        
        public TripleDESEncryptByKeyRequest() {
        }
        
        public TripleDESEncryptByKeyRequest(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptByKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rawData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyHex;
        
        public TripleDESEncryptByKeyRequestBody() {
        }
        
        public TripleDESEncryptByKeyRequestBody(string rawData, string keyHex) {
            this.rawData = rawData;
            this.keyHex = keyHex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptByKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptByKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponseBody Body;
        
        public TripleDESEncryptByKeyResponse() {
        }
        
        public TripleDESEncryptByKeyResponse(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptByKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESEncryptByKeyResult;
        
        public TripleDESEncryptByKeyResponseBody() {
        }
        
        public TripleDESEncryptByKeyResponseBody(string TripleDESEncryptByKeyResult) {
            this.TripleDESEncryptByKeyResult = TripleDESEncryptByKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptByKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptByKey", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequestBody Body;
        
        public TripleDESDecryptByKeyRequest() {
        }
        
        public TripleDESDecryptByKeyRequest(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptByKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptedHex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyHex;
        
        public TripleDESDecryptByKeyRequestBody() {
        }
        
        public TripleDESDecryptByKeyRequestBody(string encryptedHex, string keyHex) {
            this.encryptedHex = encryptedHex;
            this.keyHex = keyHex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptByKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptByKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponseBody Body;
        
        public TripleDESDecryptByKeyResponse() {
        }
        
        public TripleDESDecryptByKeyResponse(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptByKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESDecryptByKeyResult;
        
        public TripleDESDecryptByKeyResponseBody() {
        }
        
        public TripleDESDecryptByKeyResponseBody(string TripleDESDecryptByKeyResult) {
            this.TripleDESDecryptByKeyResult = TripleDESDecryptByKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sign", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.SignRequestBody Body;
        
        public SignRequest() {
        }
        
        public SignRequest(ICP.Batch.AppRssPush.KeyApi.SignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyLabel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int encodeFlag;
        
        public SignRequestBody() {
        }
        
        public SignRequestBody(string data, string keyLabel, int encodeFlag) {
            this.data = data;
            this.keyLabel = keyLabel;
            this.encodeFlag = encodeFlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.SignResponseBody Body;
        
        public SignResponse() {
        }
        
        public SignResponse(ICP.Batch.AppRssPush.KeyApi.SignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignResult;
        
        public SignResponseBody() {
        }
        
        public SignResponseBody(string SignResult) {
            this.SignResult = SignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySign", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.VerifySignRequestBody Body;
        
        public VerifySignRequest() {
        }
        
        public VerifySignRequest(ICP.Batch.AppRssPush.KeyApi.VerifySignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifySignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyLabel;
        
        public VerifySignRequestBody() {
        }
        
        public VerifySignRequestBody(string signData, string keyLabel) {
            this.signData = signData;
            this.keyLabel = keyLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.VerifySignResponseBody Body;
        
        public VerifySignResponse() {
        }
        
        public VerifySignResponse(ICP.Batch.AppRssPush.KeyApi.VerifySignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifySignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifySignResult;
        
        public VerifySignResponseBody() {
        }
        
        public VerifySignResponseBody(bool VerifySignResult) {
            this.VerifySignResult = VerifySignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignTest", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.SignTestRequestBody Body;
        
        public SignTestRequest() {
        }
        
        public SignTestRequest(ICP.Batch.AppRssPush.KeyApi.SignTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int encodeFlag;
        
        public SignTestRequestBody() {
        }
        
        public SignTestRequestBody(string bankCode, string data, int encodeFlag) {
            this.bankCode = bankCode;
            this.data = data;
            this.encodeFlag = encodeFlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.SignTestResponseBody Body;
        
        public SignTestResponse() {
        }
        
        public SignTestResponse(ICP.Batch.AppRssPush.KeyApi.SignTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignTestResult;
        
        public SignTestResponseBody() {
        }
        
        public SignTestResponseBody(string SignTestResult) {
            this.SignTestResult = SignTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySignTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySignTest", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequestBody Body;
        
        public VerifySignTestRequest() {
        }
        
        public VerifySignTestRequest(ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifySignTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string signData;
        
        public VerifySignTestRequestBody() {
        }
        
        public VerifySignTestRequestBody(string bankCode, string signData) {
            this.bankCode = bankCode;
            this.signData = signData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySignTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySignTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponseBody Body;
        
        public VerifySignTestResponse() {
        }
        
        public VerifySignTestResponse(ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifySignTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifySignTestResult;
        
        public VerifySignTestResponseBody() {
        }
        
        public VerifySignTestResponseBody(bool VerifySignTestResult) {
            this.VerifySignTestResult = VerifySignTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeyApiSoapChannel : ICP.Batch.AppRssPush.KeyApi.KeyApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyApiSoapClient : System.ServiceModel.ClientBase<ICP.Batch.AppRssPush.KeyApi.KeyApiSoap>, ICP.Batch.AppRssPush.KeyApi.KeyApiSoap {
        
        public KeyApiSoapClient() {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.GetValueResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.GetValue(ICP.Batch.AppRssPush.KeyApi.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string key) {
            ICP.Batch.AppRssPush.KeyApi.GetValueRequest inValue = new ICP.Batch.AppRssPush.KeyApi.GetValueRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.GetValueRequestBody();
            inValue.Body.key = key;
            ICP.Batch.AppRssPush.KeyApi.GetValueResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).GetValue(inValue);
            return retVal.Body.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.GetValueResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.GetValueAsync(ICP.Batch.AppRssPush.KeyApi.GetValueRequest request) {
            return base.Channel.GetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.GetValueResponse> GetValueAsync(string key) {
            ICP.Batch.AppRssPush.KeyApi.GetValueRequest inValue = new ICP.Batch.AppRssPush.KeyApi.GetValueRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.GetValueRequestBody();
            inValue.Body.key = key;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).GetValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESEncrypt(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest request) {
            return base.Channel.TripleDESEncrypt(request);
        }
        
        public string TripleDESEncrypt(string rawData, string keyLabel) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyLabel = keyLabel;
            ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESEncrypt(inValue);
            return retVal.Body.TripleDESEncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESEncryptAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest request) {
            return base.Channel.TripleDESEncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptResponse> TripleDESEncryptAsync(string rawData, string keyLabel) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyLabel = keyLabel;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESEncryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESDecrypt(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest request) {
            return base.Channel.TripleDESDecrypt(request);
        }
        
        public string TripleDESDecrypt(string encryptedHex, string keyLabel) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyLabel = keyLabel;
            ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESDecrypt(inValue);
            return retVal.Body.TripleDESDecryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESDecryptAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest request) {
            return base.Channel.TripleDESDecryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptResponse> TripleDESDecryptAsync(string encryptedHex, string keyLabel) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyLabel = keyLabel;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESDecryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESEncryptByKey(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest request) {
            return base.Channel.TripleDESEncryptByKey(request);
        }
        
        public string TripleDESEncryptByKey(string rawData, string keyHex) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyHex = keyHex;
            ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESEncryptByKey(inValue);
            return retVal.Body.TripleDESEncryptByKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESEncryptByKeyAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest request) {
            return base.Channel.TripleDESEncryptByKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyResponse> TripleDESEncryptByKeyAsync(string rawData, string keyHex) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESEncryptByKeyRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyHex = keyHex;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESEncryptByKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESDecryptByKey(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest request) {
            return base.Channel.TripleDESDecryptByKey(request);
        }
        
        public string TripleDESDecryptByKey(string encryptedHex, string keyHex) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyHex = keyHex;
            ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESDecryptByKey(inValue);
            return retVal.Body.TripleDESDecryptByKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.TripleDESDecryptByKeyAsync(ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest request) {
            return base.Channel.TripleDESDecryptByKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyResponse> TripleDESDecryptByKeyAsync(string encryptedHex, string keyHex) {
            ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest inValue = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.TripleDESDecryptByKeyRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyHex = keyHex;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).TripleDESDecryptByKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.SignResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.Sign(ICP.Batch.AppRssPush.KeyApi.SignRequest request) {
            return base.Channel.Sign(request);
        }
        
        public string Sign(string data, string keyLabel, int encodeFlag) {
            ICP.Batch.AppRssPush.KeyApi.SignRequest inValue = new ICP.Batch.AppRssPush.KeyApi.SignRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.SignRequestBody();
            inValue.Body.data = data;
            inValue.Body.keyLabel = keyLabel;
            inValue.Body.encodeFlag = encodeFlag;
            ICP.Batch.AppRssPush.KeyApi.SignResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).Sign(inValue);
            return retVal.Body.SignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.SignResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.SignAsync(ICP.Batch.AppRssPush.KeyApi.SignRequest request) {
            return base.Channel.SignAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.SignResponse> SignAsync(string data, string keyLabel, int encodeFlag) {
            ICP.Batch.AppRssPush.KeyApi.SignRequest inValue = new ICP.Batch.AppRssPush.KeyApi.SignRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.SignRequestBody();
            inValue.Body.data = data;
            inValue.Body.keyLabel = keyLabel;
            inValue.Body.encodeFlag = encodeFlag;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).SignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.VerifySignResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.VerifySign(ICP.Batch.AppRssPush.KeyApi.VerifySignRequest request) {
            return base.Channel.VerifySign(request);
        }
        
        public bool VerifySign(string signData, string keyLabel) {
            ICP.Batch.AppRssPush.KeyApi.VerifySignRequest inValue = new ICP.Batch.AppRssPush.KeyApi.VerifySignRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.VerifySignRequestBody();
            inValue.Body.signData = signData;
            inValue.Body.keyLabel = keyLabel;
            ICP.Batch.AppRssPush.KeyApi.VerifySignResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).VerifySign(inValue);
            return retVal.Body.VerifySignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.VerifySignResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.VerifySignAsync(ICP.Batch.AppRssPush.KeyApi.VerifySignRequest request) {
            return base.Channel.VerifySignAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.VerifySignResponse> VerifySignAsync(string signData, string keyLabel) {
            ICP.Batch.AppRssPush.KeyApi.VerifySignRequest inValue = new ICP.Batch.AppRssPush.KeyApi.VerifySignRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.VerifySignRequestBody();
            inValue.Body.signData = signData;
            inValue.Body.keyLabel = keyLabel;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).VerifySignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.SignTestResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.SignTest(ICP.Batch.AppRssPush.KeyApi.SignTestRequest request) {
            return base.Channel.SignTest(request);
        }
        
        public string SignTest(string bankCode, string data, int encodeFlag) {
            ICP.Batch.AppRssPush.KeyApi.SignTestRequest inValue = new ICP.Batch.AppRssPush.KeyApi.SignTestRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.SignTestRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.data = data;
            inValue.Body.encodeFlag = encodeFlag;
            ICP.Batch.AppRssPush.KeyApi.SignTestResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).SignTest(inValue);
            return retVal.Body.SignTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.SignTestResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.SignTestAsync(ICP.Batch.AppRssPush.KeyApi.SignTestRequest request) {
            return base.Channel.SignTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.SignTestResponse> SignTestAsync(string bankCode, string data, int encodeFlag) {
            ICP.Batch.AppRssPush.KeyApi.SignTestRequest inValue = new ICP.Batch.AppRssPush.KeyApi.SignTestRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.SignTestRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.data = data;
            inValue.Body.encodeFlag = encodeFlag;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).SignTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponse ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.VerifySignTest(ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest request) {
            return base.Channel.VerifySignTest(request);
        }
        
        public bool VerifySignTest(string bankCode, string signData) {
            ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest inValue = new ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.signData = signData;
            ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponse retVal = ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).VerifySignTest(inValue);
            return retVal.Body.VerifySignTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponse> ICP.Batch.AppRssPush.KeyApi.KeyApiSoap.VerifySignTestAsync(ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest request) {
            return base.Channel.VerifySignTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.AppRssPush.KeyApi.VerifySignTestResponse> VerifySignTestAsync(string bankCode, string signData) {
            ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest inValue = new ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequest();
            inValue.Body = new ICP.Batch.AppRssPush.KeyApi.VerifySignTestRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.signData = signData;
            return ((ICP.Batch.AppRssPush.KeyApi.KeyApiSoap)(this)).VerifySignTestAsync(inValue);
        }
    }
}
