//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Batch.ExecSendMistake.MistakeSMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MistakeTemp", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MistakeTemp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgDataField;
        
        private int SmsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendDateField;
        
        private int StatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AutoID {
            get {
                return this.AutoIDField;
            }
            set {
                if ((this.AutoIDField.Equals(value) != true)) {
                    this.AutoIDField = value;
                    this.RaisePropertyChanged("AutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgData {
            get {
                return this.MsgDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgDataField, value) != true)) {
                    this.MsgDataField = value;
                    this.RaisePropertyChanged("MsgData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SmsType {
            get {
                return this.SmsTypeField;
            }
            set {
                if ((this.SmsTypeField.Equals(value) != true)) {
                    this.SmsTypeField = value;
                    this.RaisePropertyChanged("SmsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SendDateField, value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int States {
            get {
                return this.StatesField;
            }
            set {
                if ((this.StatesField.Equals(value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccessField;
        
        private int RtnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RtnMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RtnCode {
            get {
                return this.RtnCodeField;
            }
            set {
                if ((this.RtnCodeField.Equals(value) != true)) {
                    this.RtnCodeField = value;
                    this.RaisePropertyChanged("RtnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RtnMsg {
            get {
                return this.RtnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.RtnMsgField, value) != true)) {
                    this.RtnMsgField = value;
                    this.RaisePropertyChanged("RtnMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MistakeSMS.MistakeSMSSoap")]
    public interface MistakeSMSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  ListMistakeTempResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListMistakeTemp", ReplyAction="*")]
        ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponse ListMistakeTemp(ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListMistakeTemp", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponse> ListMistakeTempAsync(ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  RtnCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateReceiveSMS", ReplyAction="*")]
        ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponse UpdateReceiveSMS(ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateReceiveSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponse> UpdateReceiveSMSAsync(ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  Phone 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MistakeUrlBody", ReplyAction="*")]
        ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponse MistakeUrlBody(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MistakeUrlBody", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponse> MistakeUrlBodyAsync(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  data 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrToModel", ReplyAction="*")]
        ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponse StrToModel(ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrToModel", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponse> StrToModelAsync(ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListMistakeTempRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListMistakeTemp", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequestBody Body;
        
        public ListMistakeTempRequest() {
        }
        
        public ListMistakeTempRequest(ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListMistakeTempRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte States;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte ChangeStates;
        
        public ListMistakeTempRequestBody() {
        }
        
        public ListMistakeTempRequestBody(byte States, byte ChangeStates) {
            this.States = States;
            this.ChangeStates = ChangeStates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListMistakeTempResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListMistakeTempResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponseBody Body;
        
        public ListMistakeTempResponse() {
        }
        
        public ListMistakeTempResponse(ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListMistakeTempResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.MistakeTemp[] ListMistakeTempResult;
        
        public ListMistakeTempResponseBody() {
        }
        
        public ListMistakeTempResponseBody(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeTemp[] ListMistakeTempResult) {
            this.ListMistakeTempResult = ListMistakeTempResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReceiveSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReceiveSMS", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequestBody Body;
        
        public UpdateReceiveSMSRequest() {
        }
        
        public UpdateReceiveSMSRequest(ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateReceiveSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AutoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RtnCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RtnMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageId;
        
        public UpdateReceiveSMSRequestBody() {
        }
        
        public UpdateReceiveSMSRequestBody(long AutoID, string RtnCode, string RtnMsg, string MessageId) {
            this.AutoID = AutoID;
            this.RtnCode = RtnCode;
            this.RtnMsg = RtnMsg;
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReceiveSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReceiveSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponseBody Body;
        
        public UpdateReceiveSMSResponse() {
        }
        
        public UpdateReceiveSMSResponse(ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateReceiveSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.BaseResult UpdateReceiveSMSResult;
        
        public UpdateReceiveSMSResponseBody() {
        }
        
        public UpdateReceiveSMSResponseBody(ICP.Batch.ExecSendMistake.MistakeSMS.BaseResult UpdateReceiveSMSResult) {
            this.UpdateReceiveSMSResult = UpdateReceiveSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MistakeUrlBodyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MistakeUrlBody", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequestBody Body;
        
        public MistakeUrlBodyRequest() {
        }
        
        public MistakeUrlBodyRequest(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MistakeUrlBodyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgData;
        
        public MistakeUrlBodyRequestBody() {
        }
        
        public MistakeUrlBodyRequestBody(string Phone, string GUID, string MsgData) {
            this.Phone = Phone;
            this.GUID = GUID;
            this.MsgData = MsgData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MistakeUrlBodyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MistakeUrlBodyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponseBody Body;
        
        public MistakeUrlBodyResponse() {
        }
        
        public MistakeUrlBodyResponse(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MistakeUrlBodyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MistakeUrlBodyResult;
        
        public MistakeUrlBodyResponseBody() {
        }
        
        public MistakeUrlBodyResponseBody(string MistakeUrlBodyResult) {
            this.MistakeUrlBodyResult = MistakeUrlBodyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrToModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrToModel", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequestBody Body;
        
        public StrToModelRequest() {
        }
        
        public StrToModelRequest(ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrToModelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AutoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public StrToModelRequestBody() {
        }
        
        public StrToModelRequestBody(long AutoID, string data) {
            this.AutoID = AutoID;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrToModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrToModelResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponseBody Body;
        
        public StrToModelResponse() {
        }
        
        public StrToModelResponse(ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrToModelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Batch.ExecSendMistake.MistakeSMS.BaseResult StrToModelResult;
        
        public StrToModelResponseBody() {
        }
        
        public StrToModelResponseBody(ICP.Batch.ExecSendMistake.MistakeSMS.BaseResult StrToModelResult) {
            this.StrToModelResult = StrToModelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MistakeSMSSoapChannel : ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MistakeSMSSoapClient : System.ServiceModel.ClientBase<ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap>, ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap {
        
        public MistakeSMSSoapClient() {
        }
        
        public MistakeSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MistakeSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MistakeSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MistakeSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponse ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.ListMistakeTemp(ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest request) {
            return base.Channel.ListMistakeTemp(request);
        }
        
        public ICP.Batch.ExecSendMistake.MistakeSMS.MistakeTemp[] ListMistakeTemp(byte States, byte ChangeStates) {
            ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequestBody();
            inValue.Body.States = States;
            inValue.Body.ChangeStates = ChangeStates;
            ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponse retVal = ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).ListMistakeTemp(inValue);
            return retVal.Body.ListMistakeTempResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponse> ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.ListMistakeTempAsync(ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest request) {
            return base.Channel.ListMistakeTempAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempResponse> ListMistakeTempAsync(byte States, byte ChangeStates) {
            ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.ListMistakeTempRequestBody();
            inValue.Body.States = States;
            inValue.Body.ChangeStates = ChangeStates;
            return ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).ListMistakeTempAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponse ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.UpdateReceiveSMS(ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest request) {
            return base.Channel.UpdateReceiveSMS(request);
        }
        
        public ICP.Batch.ExecSendMistake.MistakeSMS.BaseResult UpdateReceiveSMS(long AutoID, string RtnCode, string RtnMsg, string MessageId) {
            ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequestBody();
            inValue.Body.AutoID = AutoID;
            inValue.Body.RtnCode = RtnCode;
            inValue.Body.RtnMsg = RtnMsg;
            inValue.Body.MessageId = MessageId;
            ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponse retVal = ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).UpdateReceiveSMS(inValue);
            return retVal.Body.UpdateReceiveSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponse> ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.UpdateReceiveSMSAsync(ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest request) {
            return base.Channel.UpdateReceiveSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSResponse> UpdateReceiveSMSAsync(long AutoID, string RtnCode, string RtnMsg, string MessageId) {
            ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.UpdateReceiveSMSRequestBody();
            inValue.Body.AutoID = AutoID;
            inValue.Body.RtnCode = RtnCode;
            inValue.Body.RtnMsg = RtnMsg;
            inValue.Body.MessageId = MessageId;
            return ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).UpdateReceiveSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponse ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.MistakeUrlBody(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest request) {
            return base.Channel.MistakeUrlBody(request);
        }
        
        public string MistakeUrlBody(string Phone, string GUID, string MsgData) {
            ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequestBody();
            inValue.Body.Phone = Phone;
            inValue.Body.GUID = GUID;
            inValue.Body.MsgData = MsgData;
            ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponse retVal = ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).MistakeUrlBody(inValue);
            return retVal.Body.MistakeUrlBodyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponse> ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.MistakeUrlBodyAsync(ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest request) {
            return base.Channel.MistakeUrlBodyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyResponse> MistakeUrlBodyAsync(string Phone, string GUID, string MsgData) {
            ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.MistakeUrlBodyRequestBody();
            inValue.Body.Phone = Phone;
            inValue.Body.GUID = GUID;
            inValue.Body.MsgData = MsgData;
            return ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).MistakeUrlBodyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponse ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.StrToModel(ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest request) {
            return base.Channel.StrToModel(request);
        }
        
        public ICP.Batch.ExecSendMistake.MistakeSMS.BaseResult StrToModel(long AutoID, string data) {
            ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequestBody();
            inValue.Body.AutoID = AutoID;
            inValue.Body.data = data;
            ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponse retVal = ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).StrToModel(inValue);
            return retVal.Body.StrToModelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponse> ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap.StrToModelAsync(ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest request) {
            return base.Channel.StrToModelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelResponse> StrToModelAsync(long AutoID, string data) {
            ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest inValue = new ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequest();
            inValue.Body = new ICP.Batch.ExecSendMistake.MistakeSMS.StrToModelRequestBody();
            inValue.Body.AutoID = AutoID;
            inValue.Body.data = data;
            return ((ICP.Batch.ExecSendMistake.MistakeSMS.MistakeSMSSoap)(this)).StrToModelAsync(inValue);
        }
    }
}
