//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Batch.InvoiceCarrierDetail.Einvoice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Einvoice.EinvoiceSoap")]
    public interface EinvoiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetBankAccount", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponse SetBankAccount(ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetBankAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponse> SetBankAccountAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierInvTitle", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponse GetCarrierInvTitle(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierInvTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponse> GetCarrierInvTitleAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierInvDetail", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponse GetCarrierInvDetail(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierInvDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponse> GetCarrierInvDetailAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeCarrierPwd", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponse ChangeCarrierPwd(ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeCarrierPwd", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponse> ChangeCarrierPwdAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotCarrierPwd", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponse ForgotCarrierPwd(ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotCarrierPwd", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponse> ForgotCarrierPwdAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierUnderType", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponse GetCarrierUnderType(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierUnderType", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponse> GetCarrierUnderTypeAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierBarcode", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponse GetCarrierBarcode(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarrierBarcode", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponse> GetCarrierBarcodeAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterCarrier", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponse RegisterCarrier(ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterCarrier", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponse> RegisterCarrierAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvDetail", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponse GetInvDetail(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponse> GetInvDetailAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  model 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvTitle", ReplyAction="*")]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponse GetInvTitle(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponse> GetInvTitleAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBankAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetBankAccount", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequestBody Body;
        
        public SetBankAccountRequest() {
        }
        
        public SetBankAccountRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetBankAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.BankAccountDTO model;
        
        public SetBankAccountRequestBody() {
        }
        
        public SetBankAccountRequestBody(ICP.Library.Services.Einvoice.BankAccountDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBankAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetBankAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponseBody Body;
        
        public SetBankAccountResponse() {
        }
        
        public SetBankAccountResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetBankAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.BankAccountResultDTO SetBankAccountResult;
        
        public SetBankAccountResponseBody() {
        }
        
        public SetBankAccountResponseBody(ICP.Library.Services.Einvoice.BankAccountResultDTO SetBankAccountResult) {
            this.SetBankAccountResult = SetBankAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierInvTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierInvTitle", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequestBody Body;
        
        public GetCarrierInvTitleRequest() {
        }
        
        public GetCarrierInvTitleRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierInvTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierInvTitleDTO model;
        
        public GetCarrierInvTitleRequestBody() {
        }
        
        public GetCarrierInvTitleRequestBody(ICP.Library.Services.Einvoice.CarrierInvTitleDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierInvTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierInvTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponseBody Body;
        
        public GetCarrierInvTitleResponse() {
        }
        
        public GetCarrierInvTitleResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierInvTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierInvTitleResultDTO GetCarrierInvTitleResult;
        
        public GetCarrierInvTitleResponseBody() {
        }
        
        public GetCarrierInvTitleResponseBody(ICP.Library.Services.Einvoice.CarrierInvTitleResultDTO GetCarrierInvTitleResult) {
            this.GetCarrierInvTitleResult = GetCarrierInvTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierInvDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierInvDetail", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequestBody Body;
        
        public GetCarrierInvDetailRequest() {
        }
        
        public GetCarrierInvDetailRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierInvDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierInvDetailDTO model;
        
        public GetCarrierInvDetailRequestBody() {
        }
        
        public GetCarrierInvDetailRequestBody(ICP.Library.Services.Einvoice.CarrierInvDetailDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierInvDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierInvDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponseBody Body;
        
        public GetCarrierInvDetailResponse() {
        }
        
        public GetCarrierInvDetailResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierInvDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierInvDetailResultDTO GetCarrierInvDetailResult;
        
        public GetCarrierInvDetailResponseBody() {
        }
        
        public GetCarrierInvDetailResponseBody(ICP.Library.Services.Einvoice.CarrierInvDetailResultDTO GetCarrierInvDetailResult) {
            this.GetCarrierInvDetailResult = GetCarrierInvDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeCarrierPwdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeCarrierPwd", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequestBody Body;
        
        public ChangeCarrierPwdRequest() {
        }
        
        public ChangeCarrierPwdRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeCarrierPwdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.ChangeCarrierPwdDTO model;
        
        public ChangeCarrierPwdRequestBody() {
        }
        
        public ChangeCarrierPwdRequestBody(ICP.Library.Services.Einvoice.ChangeCarrierPwdDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeCarrierPwdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeCarrierPwdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponseBody Body;
        
        public ChangeCarrierPwdResponse() {
        }
        
        public ChangeCarrierPwdResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeCarrierPwdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.ChangeCarrierPwdResultDTO ChangeCarrierPwdResult;
        
        public ChangeCarrierPwdResponseBody() {
        }
        
        public ChangeCarrierPwdResponseBody(ICP.Library.Services.Einvoice.ChangeCarrierPwdResultDTO ChangeCarrierPwdResult) {
            this.ChangeCarrierPwdResult = ChangeCarrierPwdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForgotCarrierPwdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForgotCarrierPwd", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequestBody Body;
        
        public ForgotCarrierPwdRequest() {
        }
        
        public ForgotCarrierPwdRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ForgotCarrierPwdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.ForgotCarrierPwdDTO model;
        
        public ForgotCarrierPwdRequestBody() {
        }
        
        public ForgotCarrierPwdRequestBody(ICP.Library.Services.Einvoice.ForgotCarrierPwdDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForgotCarrierPwdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForgotCarrierPwdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponseBody Body;
        
        public ForgotCarrierPwdResponse() {
        }
        
        public ForgotCarrierPwdResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ForgotCarrierPwdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.ForgotCarrierPwdResultDTO ForgotCarrierPwdResult;
        
        public ForgotCarrierPwdResponseBody() {
        }
        
        public ForgotCarrierPwdResponseBody(ICP.Library.Services.Einvoice.ForgotCarrierPwdResultDTO ForgotCarrierPwdResult) {
            this.ForgotCarrierPwdResult = ForgotCarrierPwdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierUnderTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierUnderType", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequestBody Body;
        
        public GetCarrierUnderTypeRequest() {
        }
        
        public GetCarrierUnderTypeRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierUnderTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierUnderTypeDTO model;
        
        public GetCarrierUnderTypeRequestBody() {
        }
        
        public GetCarrierUnderTypeRequestBody(ICP.Library.Services.Einvoice.CarrierUnderTypeDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierUnderTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierUnderTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponseBody Body;
        
        public GetCarrierUnderTypeResponse() {
        }
        
        public GetCarrierUnderTypeResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierUnderTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierUnderTypeResultDTO GetCarrierUnderTypeResult;
        
        public GetCarrierUnderTypeResponseBody() {
        }
        
        public GetCarrierUnderTypeResponseBody(ICP.Library.Services.Einvoice.CarrierUnderTypeResultDTO GetCarrierUnderTypeResult) {
            this.GetCarrierUnderTypeResult = GetCarrierUnderTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierBarcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierBarcode", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequestBody Body;
        
        public GetCarrierBarcodeRequest() {
        }
        
        public GetCarrierBarcodeRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierBarcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierBarcodeDTO model;
        
        public GetCarrierBarcodeRequestBody() {
        }
        
        public GetCarrierBarcodeRequestBody(ICP.Library.Services.Einvoice.CarrierBarcodeDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarrierBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarrierBarcodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponseBody Body;
        
        public GetCarrierBarcodeResponse() {
        }
        
        public GetCarrierBarcodeResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarrierBarcodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.CarrierBarcodeResultDTO GetCarrierBarcodeResult;
        
        public GetCarrierBarcodeResponseBody() {
        }
        
        public GetCarrierBarcodeResponseBody(ICP.Library.Services.Einvoice.CarrierBarcodeResultDTO GetCarrierBarcodeResult) {
            this.GetCarrierBarcodeResult = GetCarrierBarcodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterCarrierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterCarrier", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequestBody Body;
        
        public RegisterCarrierRequest() {
        }
        
        public RegisterCarrierRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterCarrierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.RegisterCarrierDTO model;
        
        public RegisterCarrierRequestBody() {
        }
        
        public RegisterCarrierRequestBody(ICP.Library.Services.Einvoice.RegisterCarrierDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterCarrierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterCarrierResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponseBody Body;
        
        public RegisterCarrierResponse() {
        }
        
        public RegisterCarrierResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterCarrierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.RegisterCarrierResultDTO RegisterCarrierResult;
        
        public RegisterCarrierResponseBody() {
        }
        
        public RegisterCarrierResponseBody(ICP.Library.Services.Einvoice.RegisterCarrierResultDTO RegisterCarrierResult) {
            this.RegisterCarrierResult = RegisterCarrierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvDetail", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequestBody Body;
        
        public GetInvDetailRequest() {
        }
        
        public GetInvDetailRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInvDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.InvDetailDTO model;
        
        public GetInvDetailRequestBody() {
        }
        
        public GetInvDetailRequestBody(ICP.Library.Services.Einvoice.InvDetailDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponseBody Body;
        
        public GetInvDetailResponse() {
        }
        
        public GetInvDetailResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInvDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.InvDetailResultDTO GetInvDetailResult;
        
        public GetInvDetailResponseBody() {
        }
        
        public GetInvDetailResponseBody(ICP.Library.Services.Einvoice.InvDetailResultDTO GetInvDetailResult) {
            this.GetInvDetailResult = GetInvDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvTitle", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequestBody Body;
        
        public GetInvTitleRequest() {
        }
        
        public GetInvTitleRequest(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInvTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.InvTitleDTO model;
        
        public GetInvTitleRequestBody() {
        }
        
        public GetInvTitleRequestBody(ICP.Library.Services.Einvoice.InvTitleDTO model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponseBody Body;
        
        public GetInvTitleResponse() {
        }
        
        public GetInvTitleResponse(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInvTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Library.Services.Einvoice.InvTitleResultDTO GetInvTitleResult;
        
        public GetInvTitleResponseBody() {
        }
        
        public GetInvTitleResponseBody(ICP.Library.Services.Einvoice.InvTitleResultDTO GetInvTitleResult) {
            this.GetInvTitleResult = GetInvTitleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EinvoiceSoapChannel : ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EinvoiceSoapClient : System.ServiceModel.ClientBase<ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap>, ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap {
        
        public EinvoiceSoapClient() {
        }
        
        public EinvoiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EinvoiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EinvoiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EinvoiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.SetBankAccount(ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest request) {
            return base.Channel.SetBankAccount(request);
        }
        
        public ICP.Library.Services.Einvoice.BankAccountResultDTO SetBankAccount(ICP.Library.Services.Einvoice.BankAccountDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).SetBankAccount(inValue);
            return retVal.Body.SetBankAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.SetBankAccountAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest request) {
            return base.Channel.SetBankAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountResponse> SetBankAccountAsync(ICP.Library.Services.Einvoice.BankAccountDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.SetBankAccountRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).SetBankAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierInvTitle(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest request) {
            return base.Channel.GetCarrierInvTitle(request);
        }
        
        public ICP.Library.Services.Einvoice.CarrierInvTitleResultDTO GetCarrierInvTitle(ICP.Library.Services.Einvoice.CarrierInvTitleDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierInvTitle(inValue);
            return retVal.Body.GetCarrierInvTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierInvTitleAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest request) {
            return base.Channel.GetCarrierInvTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleResponse> GetCarrierInvTitleAsync(ICP.Library.Services.Einvoice.CarrierInvTitleDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvTitleRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierInvTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierInvDetail(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest request) {
            return base.Channel.GetCarrierInvDetail(request);
        }
        
        public ICP.Library.Services.Einvoice.CarrierInvDetailResultDTO GetCarrierInvDetail(ICP.Library.Services.Einvoice.CarrierInvDetailDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierInvDetail(inValue);
            return retVal.Body.GetCarrierInvDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierInvDetailAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest request) {
            return base.Channel.GetCarrierInvDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailResponse> GetCarrierInvDetailAsync(ICP.Library.Services.Einvoice.CarrierInvDetailDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierInvDetailRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierInvDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.ChangeCarrierPwd(ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest request) {
            return base.Channel.ChangeCarrierPwd(request);
        }
        
        public ICP.Library.Services.Einvoice.ChangeCarrierPwdResultDTO ChangeCarrierPwd(ICP.Library.Services.Einvoice.ChangeCarrierPwdDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).ChangeCarrierPwd(inValue);
            return retVal.Body.ChangeCarrierPwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.ChangeCarrierPwdAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest request) {
            return base.Channel.ChangeCarrierPwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdResponse> ChangeCarrierPwdAsync(ICP.Library.Services.Einvoice.ChangeCarrierPwdDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ChangeCarrierPwdRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).ChangeCarrierPwdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.ForgotCarrierPwd(ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest request) {
            return base.Channel.ForgotCarrierPwd(request);
        }
        
        public ICP.Library.Services.Einvoice.ForgotCarrierPwdResultDTO ForgotCarrierPwd(ICP.Library.Services.Einvoice.ForgotCarrierPwdDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).ForgotCarrierPwd(inValue);
            return retVal.Body.ForgotCarrierPwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.ForgotCarrierPwdAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest request) {
            return base.Channel.ForgotCarrierPwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdResponse> ForgotCarrierPwdAsync(ICP.Library.Services.Einvoice.ForgotCarrierPwdDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.ForgotCarrierPwdRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).ForgotCarrierPwdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierUnderType(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest request) {
            return base.Channel.GetCarrierUnderType(request);
        }
        
        public ICP.Library.Services.Einvoice.CarrierUnderTypeResultDTO GetCarrierUnderType(ICP.Library.Services.Einvoice.CarrierUnderTypeDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierUnderType(inValue);
            return retVal.Body.GetCarrierUnderTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierUnderTypeAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest request) {
            return base.Channel.GetCarrierUnderTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeResponse> GetCarrierUnderTypeAsync(ICP.Library.Services.Einvoice.CarrierUnderTypeDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierUnderTypeRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierUnderTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierBarcode(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest request) {
            return base.Channel.GetCarrierBarcode(request);
        }
        
        public ICP.Library.Services.Einvoice.CarrierBarcodeResultDTO GetCarrierBarcode(ICP.Library.Services.Einvoice.CarrierBarcodeDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierBarcode(inValue);
            return retVal.Body.GetCarrierBarcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetCarrierBarcodeAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest request) {
            return base.Channel.GetCarrierBarcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeResponse> GetCarrierBarcodeAsync(ICP.Library.Services.Einvoice.CarrierBarcodeDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetCarrierBarcodeRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetCarrierBarcodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.RegisterCarrier(ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest request) {
            return base.Channel.RegisterCarrier(request);
        }
        
        public ICP.Library.Services.Einvoice.RegisterCarrierResultDTO RegisterCarrier(ICP.Library.Services.Einvoice.RegisterCarrierDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).RegisterCarrier(inValue);
            return retVal.Body.RegisterCarrierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.RegisterCarrierAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest request) {
            return base.Channel.RegisterCarrierAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierResponse> RegisterCarrierAsync(ICP.Library.Services.Einvoice.RegisterCarrierDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.RegisterCarrierRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).RegisterCarrierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetInvDetail(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest request) {
            return base.Channel.GetInvDetail(request);
        }
        
        public ICP.Library.Services.Einvoice.InvDetailResultDTO GetInvDetail(ICP.Library.Services.Einvoice.InvDetailDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetInvDetail(inValue);
            return retVal.Body.GetInvDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetInvDetailAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest request) {
            return base.Channel.GetInvDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailResponse> GetInvDetailAsync(ICP.Library.Services.Einvoice.InvDetailDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvDetailRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetInvDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponse ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetInvTitle(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest request) {
            return base.Channel.GetInvTitle(request);
        }
        
        public ICP.Library.Services.Einvoice.InvTitleResultDTO GetInvTitle(ICP.Library.Services.Einvoice.InvTitleDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequestBody();
            inValue.Body.model = model;
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponse retVal = ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetInvTitle(inValue);
            return retVal.Body.GetInvTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponse> ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap.GetInvTitleAsync(ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest request) {
            return base.Channel.GetInvTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleResponse> GetInvTitleAsync(ICP.Library.Services.Einvoice.InvTitleDTO model) {
            ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest inValue = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequest();
            inValue.Body = new ICP.Batch.InvoiceCarrierDetail.Einvoice.GetInvTitleRequestBody();
            inValue.Body.model = model;
            return ((ICP.Batch.InvoiceCarrierDetail.Einvoice.EinvoiceSoap)(this)).GetInvTitleAsync(inValue);
        }
    }
}
