//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Library.Services.PersonalAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonalAuth.PersonalAuthSoap")]
    public interface PersonalAuthSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P33Auth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        ICP.Library.Services.PersonalAuth.P33AuthResult P33Auth(ICP.Library.Services.PersonalAuth.P33Auth model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P33Auth", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Library.Services.PersonalAuth.P33AuthResult> P33AuthAsync(ICP.Library.Services.PersonalAuth.P33Auth model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P11Auth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        ICP.Library.Services.PersonalAuth.P11AuthResult P11Auth(ICP.Library.Services.PersonalAuth.P11Auth model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P11Auth", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Library.Services.PersonalAuth.P11AuthResult> P11AuthAsync(ICP.Library.Services.PersonalAuth.P11Auth model);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class P33Auth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long mIDField;
        
        private string iDNOField;
        
        private string userNameField;
        
        private byte sourceField;
        
        private long realIPField;
        
        private long proxyIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MID {
            get {
                return this.mIDField;
            }
            set {
                this.mIDField = value;
                this.RaisePropertyChanged("MID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IDNO {
            get {
                return this.iDNOField;
            }
            set {
                this.iDNOField = value;
                this.RaisePropertyChanged("IDNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long RealIP {
            get {
                return this.realIPField;
            }
            set {
                this.realIPField = value;
                this.RaisePropertyChanged("RealIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long ProxyIP {
            get {
                return this.proxyIPField;
            }
            set {
                this.proxyIPField = value;
                this.RaisePropertyChanged("ProxyIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class P11Auth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long mIDField;
        
        private string iDNOField;
        
        private string issueDateField;
        
        private int issueTypeField;
        
        private string birthDateField;
        
        private int picFreeField;
        
        private string issueLocField;
        
        private int sourceField;
        
        private string userNameField;
        
        private long realIPField;
        
        private long proxyIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MID {
            get {
                return this.mIDField;
            }
            set {
                this.mIDField = value;
                this.RaisePropertyChanged("MID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IDNO {
            get {
                return this.iDNOField;
            }
            set {
                this.iDNOField = value;
                this.RaisePropertyChanged("IDNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IssueType {
            get {
                return this.issueTypeField;
            }
            set {
                this.issueTypeField = value;
                this.RaisePropertyChanged("IssueType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PicFree {
            get {
                return this.picFreeField;
            }
            set {
                this.picFreeField = value;
                this.RaisePropertyChanged("PicFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IssueLoc {
            get {
                return this.issueLocField;
            }
            set {
                this.issueLocField = value;
                this.RaisePropertyChanged("IssueLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long RealIP {
            get {
                return this.realIPField;
            }
            set {
                this.realIPField = value;
                this.RaisePropertyChanged("RealIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long ProxyIP {
            get {
                return this.proxyIPField;
            }
            set {
                this.proxyIPField = value;
                this.RaisePropertyChanged("ProxyIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(P11AuthResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(P33AuthResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSuccessField;
        
        private int rtnCodeField;
        
        private string rtnMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RtnCode {
            get {
                return this.rtnCodeField;
            }
            set {
                this.rtnCodeField = value;
                this.RaisePropertyChanged("RtnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RtnMsg {
            get {
                return this.rtnMsgField;
            }
            set {
                this.rtnMsgField = value;
                this.RaisePropertyChanged("RtnMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class P11AuthResult : BaseResult {
        
        private short isPassField;
        
        private string answerField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short IsPass {
            get {
                return this.isPassField;
            }
            set {
                this.isPassField = value;
                this.RaisePropertyChanged("IsPass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Answer {
            get {
                return this.answerField;
            }
            set {
                this.answerField = value;
                this.RaisePropertyChanged("Answer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class P33AuthResult : BaseResult {
        
        private short isPassField;
        
        private int dataCountField;
        
        private string dataListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short IsPass {
            get {
                return this.isPassField;
            }
            set {
                this.isPassField = value;
                this.RaisePropertyChanged("IsPass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DataCount {
            get {
                return this.dataCountField;
            }
            set {
                this.dataCountField = value;
                this.RaisePropertyChanged("DataCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataList {
            get {
                return this.dataListField;
            }
            set {
                this.dataListField = value;
                this.RaisePropertyChanged("DataList");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonalAuthSoapChannel : ICP.Library.Services.PersonalAuth.PersonalAuthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonalAuthSoapClient : System.ServiceModel.ClientBase<ICP.Library.Services.PersonalAuth.PersonalAuthSoap>, ICP.Library.Services.PersonalAuth.PersonalAuthSoap {
        
        public PersonalAuthSoapClient() {
        }
        
        public PersonalAuthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalAuthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalAuthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalAuthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ICP.Library.Services.PersonalAuth.P33AuthResult P33Auth(ICP.Library.Services.PersonalAuth.P33Auth model) {
            return base.Channel.P33Auth(model);
        }
        
        public System.Threading.Tasks.Task<ICP.Library.Services.PersonalAuth.P33AuthResult> P33AuthAsync(ICP.Library.Services.PersonalAuth.P33Auth model) {
            return base.Channel.P33AuthAsync(model);
        }
        
        public ICP.Library.Services.PersonalAuth.P11AuthResult P11Auth(ICP.Library.Services.PersonalAuth.P11Auth model) {
            return base.Channel.P11Auth(model);
        }
        
        public System.Threading.Tasks.Task<ICP.Library.Services.PersonalAuth.P11AuthResult> P11AuthAsync(ICP.Library.Services.PersonalAuth.P11Auth model) {
            return base.Channel.P11AuthAsync(model);
        }
    }
}
