//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Infrastructure.Core.KeyApiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeyApiServiceReference.KeyApiSoap")]
    public interface KeyApiSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  key 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponse GetValue(ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponse> GetValueAsync(ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValue", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequestBody Body;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetValueRequestBody() {
        }
        
        public GetValueRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponseBody Body;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValueResult;
        
        public GetValueResponseBody() {
        }
        
        public GetValueResponseBody(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeyApiSoapChannel : ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyApiSoapClient : System.ServiceModel.ClientBase<ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap>, ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap {
        
        public KeyApiSoapClient() {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponse ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap.GetValue(ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string key) {
            ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest inValue = new ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest();
            inValue.Body = new ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequestBody();
            inValue.Body.key = key;
            ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponse retVal = ((ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap)(this)).GetValue(inValue);
            return retVal.Body.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponse> ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap.GetValueAsync(ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest request) {
            return base.Channel.GetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Infrastructure.Core.KeyApiServiceReference.GetValueResponse> GetValueAsync(string key) {
            ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest inValue = new ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequest();
            inValue.Body = new ICP.Infrastructure.Core.KeyApiServiceReference.GetValueRequestBody();
            inValue.Body.key = key;
            return ((ICP.Infrastructure.Core.KeyApiServiceReference.KeyApiSoap)(this)).GetValueAsync(inValue);
        }
    }
}
