//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Modules.Api.AccountLink.KeyApiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeyApiServiceReference.KeyApiSoap")]
    public interface KeyApiSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  key 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponse GetValue(ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponse> GetValueAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  rawData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncrypt", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse TripleDESEncrypt(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse> TripleDESEncryptAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  encryptedHex 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecrypt", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse TripleDESDecrypt(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse> TripleDESDecryptAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  rawData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncryptByKey", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponse TripleDESEncryptByKey(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESEncryptByKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponse> TripleDESEncryptByKeyAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  encryptedHex 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecryptByKey", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponse TripleDESDecryptByKey(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TripleDESDecryptByKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponse> TripleDESDecryptByKeyAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  bankCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sign", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponse Sign(ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sign", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponse> SignAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  bankCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySign", ReplyAction="*")]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponse VerifySign(ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySign", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponse> VerifySignAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValue", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequestBody Body;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetValueRequestBody() {
        }
        
        public GetValueRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponseBody Body;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValueResult;
        
        public GetValueResponseBody() {
        }
        
        public GetValueResponseBody(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncrypt", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody Body;
        
        public TripleDESEncryptRequest() {
        }
        
        public TripleDESEncryptRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rawData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyLabel;
        
        public TripleDESEncryptRequestBody() {
        }
        
        public TripleDESEncryptRequestBody(string rawData, string keyLabel) {
            this.rawData = rawData;
            this.keyLabel = keyLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponseBody Body;
        
        public TripleDESEncryptResponse() {
        }
        
        public TripleDESEncryptResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESEncryptResult;
        
        public TripleDESEncryptResponseBody() {
        }
        
        public TripleDESEncryptResponseBody(string TripleDESEncryptResult) {
            this.TripleDESEncryptResult = TripleDESEncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecrypt", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody Body;
        
        public TripleDESDecryptRequest() {
        }
        
        public TripleDESDecryptRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptedHex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyLabel;
        
        public TripleDESDecryptRequestBody() {
        }
        
        public TripleDESDecryptRequestBody(string encryptedHex, string keyLabel) {
            this.encryptedHex = encryptedHex;
            this.keyLabel = keyLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponseBody Body;
        
        public TripleDESDecryptResponse() {
        }
        
        public TripleDESDecryptResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESDecryptResult;
        
        public TripleDESDecryptResponseBody() {
        }
        
        public TripleDESDecryptResponseBody(string TripleDESDecryptResult) {
            this.TripleDESDecryptResult = TripleDESDecryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptByKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptByKey", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequestBody Body;
        
        public TripleDESEncryptByKeyRequest() {
        }
        
        public TripleDESEncryptByKeyRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptByKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rawData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyHex;
        
        public TripleDESEncryptByKeyRequestBody() {
        }
        
        public TripleDESEncryptByKeyRequestBody(string rawData, string keyHex) {
            this.rawData = rawData;
            this.keyHex = keyHex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESEncryptByKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESEncryptByKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponseBody Body;
        
        public TripleDESEncryptByKeyResponse() {
        }
        
        public TripleDESEncryptByKeyResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESEncryptByKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESEncryptByKeyResult;
        
        public TripleDESEncryptByKeyResponseBody() {
        }
        
        public TripleDESEncryptByKeyResponseBody(string TripleDESEncryptByKeyResult) {
            this.TripleDESEncryptByKeyResult = TripleDESEncryptByKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptByKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptByKey", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequestBody Body;
        
        public TripleDESDecryptByKeyRequest() {
        }
        
        public TripleDESDecryptByKeyRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptByKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptedHex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyHex;
        
        public TripleDESDecryptByKeyRequestBody() {
        }
        
        public TripleDESDecryptByKeyRequestBody(string encryptedHex, string keyHex) {
            this.encryptedHex = encryptedHex;
            this.keyHex = keyHex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TripleDESDecryptByKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TripleDESDecryptByKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponseBody Body;
        
        public TripleDESDecryptByKeyResponse() {
        }
        
        public TripleDESDecryptByKeyResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TripleDESDecryptByKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripleDESDecryptByKeyResult;
        
        public TripleDESDecryptByKeyResponseBody() {
        }
        
        public TripleDESDecryptByKeyResponseBody(string TripleDESDecryptByKeyResult) {
            this.TripleDESDecryptByKeyResult = TripleDESDecryptByKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sign", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequestBody Body;
        
        public SignRequest() {
        }
        
        public SignRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string keyLabel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string certId;
        
        public SignRequestBody() {
        }
        
        public SignRequestBody(string bankCode, string data, string keyLabel, string certId) {
            this.bankCode = bankCode;
            this.data = data;
            this.keyLabel = keyLabel;
            this.certId = certId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponseBody Body;
        
        public SignResponse() {
        }
        
        public SignResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignResult;
        
        public SignResponseBody() {
        }
        
        public SignResponseBody(string SignResult) {
            this.SignResult = SignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySign", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequestBody Body;
        
        public VerifySignRequest() {
        }
        
        public VerifySignRequest(ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifySignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string signDataHex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string keyLabel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string certId;
        
        public VerifySignRequestBody() {
        }
        
        public VerifySignRequestBody(string bankCode, string signDataHex, string keyLabel, string certId) {
            this.bankCode = bankCode;
            this.signDataHex = signDataHex;
            this.keyLabel = keyLabel;
            this.certId = certId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponseBody Body;
        
        public VerifySignResponse() {
        }
        
        public VerifySignResponse(ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifySignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifySignResult;
        
        public VerifySignResponseBody() {
        }
        
        public VerifySignResponseBody(bool VerifySignResult) {
            this.VerifySignResult = VerifySignResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeyApiSoapChannel : ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyApiSoapClient : System.ServiceModel.ClientBase<ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap>, ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap {
        
        public KeyApiSoapClient() {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.GetValue(ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string key) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequestBody();
            inValue.Body.key = key;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).GetValue(inValue);
            return retVal.Body.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.GetValueAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest request) {
            return base.Channel.GetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueResponse> GetValueAsync(string key) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.GetValueRequestBody();
            inValue.Body.key = key;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).GetValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESEncrypt(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request) {
            return base.Channel.TripleDESEncrypt(request);
        }
        
        public string TripleDESEncrypt(string rawData, string keyLabel) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyLabel = keyLabel;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESEncrypt(inValue);
            return retVal.Body.TripleDESEncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESEncryptAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest request) {
            return base.Channel.TripleDESEncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptResponse> TripleDESEncryptAsync(string rawData, string keyLabel) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyLabel = keyLabel;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESEncryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESDecrypt(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request) {
            return base.Channel.TripleDESDecrypt(request);
        }
        
        public string TripleDESDecrypt(string encryptedHex, string keyLabel) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyLabel = keyLabel;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESDecrypt(inValue);
            return retVal.Body.TripleDESDecryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESDecryptAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest request) {
            return base.Channel.TripleDESDecryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptResponse> TripleDESDecryptAsync(string encryptedHex, string keyLabel) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyLabel = keyLabel;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESDecryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESEncryptByKey(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest request) {
            return base.Channel.TripleDESEncryptByKey(request);
        }
        
        public string TripleDESEncryptByKey(string rawData, string keyHex) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyHex = keyHex;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESEncryptByKey(inValue);
            return retVal.Body.TripleDESEncryptByKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESEncryptByKeyAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest request) {
            return base.Channel.TripleDESEncryptByKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyResponse> TripleDESEncryptByKeyAsync(string rawData, string keyHex) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESEncryptByKeyRequestBody();
            inValue.Body.rawData = rawData;
            inValue.Body.keyHex = keyHex;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESEncryptByKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESDecryptByKey(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest request) {
            return base.Channel.TripleDESDecryptByKey(request);
        }
        
        public string TripleDESDecryptByKey(string encryptedHex, string keyHex) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyHex = keyHex;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESDecryptByKey(inValue);
            return retVal.Body.TripleDESDecryptByKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.TripleDESDecryptByKeyAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest request) {
            return base.Channel.TripleDESDecryptByKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyResponse> TripleDESDecryptByKeyAsync(string encryptedHex, string keyHex) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.TripleDESDecryptByKeyRequestBody();
            inValue.Body.encryptedHex = encryptedHex;
            inValue.Body.keyHex = keyHex;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).TripleDESDecryptByKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.Sign(ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest request) {
            return base.Channel.Sign(request);
        }
        
        public string Sign(string bankCode, string data, string keyLabel, string certId) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.data = data;
            inValue.Body.keyLabel = keyLabel;
            inValue.Body.certId = certId;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).Sign(inValue);
            return retVal.Body.SignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.SignAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest request) {
            return base.Channel.SignAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignResponse> SignAsync(string bankCode, string data, string keyLabel, string certId) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.SignRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.data = data;
            inValue.Body.keyLabel = keyLabel;
            inValue.Body.certId = certId;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).SignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponse ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.VerifySign(ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest request) {
            return base.Channel.VerifySign(request);
        }
        
        public bool VerifySign(string bankCode, string signDataHex, string keyLabel, string certId) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.signDataHex = signDataHex;
            inValue.Body.keyLabel = keyLabel;
            inValue.Body.certId = certId;
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponse retVal = ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).VerifySign(inValue);
            return retVal.Body.VerifySignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponse> ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap.VerifySignAsync(ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest request) {
            return base.Channel.VerifySignAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignResponse> VerifySignAsync(string bankCode, string signDataHex, string keyLabel, string certId) {
            ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest inValue = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequest();
            inValue.Body = new ICP.Modules.Api.AccountLink.KeyApiServiceReference.VerifySignRequestBody();
            inValue.Body.bankCode = bankCode;
            inValue.Body.signDataHex = signDataHex;
            inValue.Body.keyLabel = keyLabel;
            inValue.Body.certId = certId;
            return ((ICP.Modules.Api.AccountLink.KeyApiServiceReference.KeyApiSoap)(this)).VerifySignAsync(inValue);
        }
    }
}
