//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.Batch.ExecSendFETSMS.FETSMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FETTemp", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FETTemp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgDataField;
        
        private System.Nullable<byte> SmsTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AutoID {
            get {
                return this.AutoIDField;
            }
            set {
                if ((this.AutoIDField.Equals(value) != true)) {
                    this.AutoIDField = value;
                    this.RaisePropertyChanged("AutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgData {
            get {
                return this.MsgDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgDataField, value) != true)) {
                    this.MsgDataField = value;
                    this.RaisePropertyChanged("MsgData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<byte> SmsType {
            get {
                return this.SmsTypeField;
            }
            set {
                if ((this.SmsTypeField.Equals(value) != true)) {
                    this.SmsTypeField = value;
                    this.RaisePropertyChanged("SmsType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccessField;
        
        private int RtnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RtnMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RtnCode {
            get {
                return this.RtnCodeField;
            }
            set {
                if ((this.RtnCodeField.Equals(value) != true)) {
                    this.RtnCodeField = value;
                    this.RaisePropertyChanged("RtnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RtnMsg {
            get {
                return this.RtnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.RtnMsgField, value) != true)) {
                    this.RtnMsgField = value;
                    this.RaisePropertyChanged("RtnMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FETSMS.FETSMSSoap")]
    public interface FETSMSSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  ListFetTempResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListFetTemp", ReplyAction="*")]
        ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponse ListFetTemp(ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListFetTemp", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponse> ListFetTempAsync(ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  RtnCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateReceiveSMS", ReplyAction="*")]
        ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponse UpdateReceiveSMS(ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateReceiveSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponse> UpdateReceiveSMSAsync(ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFetTempRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFetTemp", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequestBody Body;
        
        public ListFetTempRequest() {
        }
        
        public ListFetTempRequest(ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListFetTempRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte States;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte ChangeStates;
        
        public ListFetTempRequestBody() {
        }
        
        public ListFetTempRequestBody(byte States, byte ChangeStates) {
            this.States = States;
            this.ChangeStates = ChangeStates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFetTempResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFetTempResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponseBody Body;
        
        public ListFetTempResponse() {
        }
        
        public ListFetTempResponse(ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListFetTempResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Batch.ExecSendFETSMS.FETSMS.FETTemp[] ListFetTempResult;
        
        public ListFetTempResponseBody() {
        }
        
        public ListFetTempResponseBody(ICP.Batch.ExecSendFETSMS.FETSMS.FETTemp[] ListFetTempResult) {
            this.ListFetTempResult = ListFetTempResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReceiveSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReceiveSMS", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequestBody Body;
        
        public UpdateReceiveSMSRequest() {
        }
        
        public UpdateReceiveSMSRequest(ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateReceiveSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AutoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RtnCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RtnMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageId;
        
        public UpdateReceiveSMSRequestBody() {
        }
        
        public UpdateReceiveSMSRequestBody(long AutoID, string RtnCode, string RtnMsg, string MessageId) {
            this.AutoID = AutoID;
            this.RtnCode = RtnCode;
            this.RtnMsg = RtnMsg;
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReceiveSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReceiveSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponseBody Body;
        
        public UpdateReceiveSMSResponse() {
        }
        
        public UpdateReceiveSMSResponse(ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateReceiveSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICP.Batch.ExecSendFETSMS.FETSMS.BaseResult UpdateReceiveSMSResult;
        
        public UpdateReceiveSMSResponseBody() {
        }
        
        public UpdateReceiveSMSResponseBody(ICP.Batch.ExecSendFETSMS.FETSMS.BaseResult UpdateReceiveSMSResult) {
            this.UpdateReceiveSMSResult = UpdateReceiveSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FETSMSSoapChannel : ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FETSMSSoapClient : System.ServiceModel.ClientBase<ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap>, ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap {
        
        public FETSMSSoapClient() {
        }
        
        public FETSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FETSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FETSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FETSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponse ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap.ListFetTemp(ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest request) {
            return base.Channel.ListFetTemp(request);
        }
        
        public ICP.Batch.ExecSendFETSMS.FETSMS.FETTemp[] ListFetTemp(byte States, byte ChangeStates) {
            ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest inValue = new ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest();
            inValue.Body = new ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequestBody();
            inValue.Body.States = States;
            inValue.Body.ChangeStates = ChangeStates;
            ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponse retVal = ((ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap)(this)).ListFetTemp(inValue);
            return retVal.Body.ListFetTempResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponse> ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap.ListFetTempAsync(ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest request) {
            return base.Channel.ListFetTempAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempResponse> ListFetTempAsync(byte States, byte ChangeStates) {
            ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest inValue = new ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequest();
            inValue.Body = new ICP.Batch.ExecSendFETSMS.FETSMS.ListFetTempRequestBody();
            inValue.Body.States = States;
            inValue.Body.ChangeStates = ChangeStates;
            return ((ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap)(this)).ListFetTempAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponse ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap.UpdateReceiveSMS(ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest request) {
            return base.Channel.UpdateReceiveSMS(request);
        }
        
        public ICP.Batch.ExecSendFETSMS.FETSMS.BaseResult UpdateReceiveSMS(long AutoID, string RtnCode, string RtnMsg, string MessageId) {
            ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest inValue = new ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest();
            inValue.Body = new ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequestBody();
            inValue.Body.AutoID = AutoID;
            inValue.Body.RtnCode = RtnCode;
            inValue.Body.RtnMsg = RtnMsg;
            inValue.Body.MessageId = MessageId;
            ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponse retVal = ((ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap)(this)).UpdateReceiveSMS(inValue);
            return retVal.Body.UpdateReceiveSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponse> ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap.UpdateReceiveSMSAsync(ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest request) {
            return base.Channel.UpdateReceiveSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSResponse> UpdateReceiveSMSAsync(long AutoID, string RtnCode, string RtnMsg, string MessageId) {
            ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest inValue = new ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequest();
            inValue.Body = new ICP.Batch.ExecSendFETSMS.FETSMS.UpdateReceiveSMSRequestBody();
            inValue.Body.AutoID = AutoID;
            inValue.Body.RtnCode = RtnCode;
            inValue.Body.RtnMsg = RtnMsg;
            inValue.Body.MessageId = MessageId;
            return ((ICP.Batch.ExecSendFETSMS.FETSMS.FETSMSSoap)(this)).UpdateReceiveSMSAsync(inValue);
        }
    }
}
